services:
  nginx:
    image: nginx
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      -   "8876:80"
    depends_on:
      -   app
    container_name: nginx-imtera
    networks:
      - imtera_test

  app:
      build:
          context: .
          dockerfile: _docker/app/Dockerfile
      volumes:
          - ./:/var/www
      ports:
          - "5173:5173"
      extra_hosts:
          - "host.docker.internal:host-gateway"
      depends_on:
          - db
      container_name: app-imtera
      networks:
          - imtera_test

  db:
    image: mysql:8.0
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      -   ./tmp/db:/var/lib/mysql
    container_name: mysql-imtera
    networks:
      - imtera_test

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
    container_name: phpmyadmin-imtera
    networks:
      - imtera_test

networks:
   imtera_test:
    driver: bridge
